/**
 * X.10 validation gate — the pure engine, run on REAL backfilled QQQ data,
 * must reproduce total return matching two INDEPENDENT references:
 *   - a Python DRIP reimplementation on the same raw close + dividends
 *   - yfinance Adj Close ratio (external authoritative source)
 * Fixture generated by apps/stock_collector/x_backtest_gate.py.
 */
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import { runBacktest } from './engine';
import type { BacktestInput, PricePoint } from '@/types/backtest';

type Fixture = {
    label: string;
    from: string;
    to: string;
    series: PricePoint[];
    expected: { pyDrip: number; yfAdjClose?: number };
};

const fixture: Fixture = JSON.parse(
    readFileSync(
        join(__dirname, '__fixtures__/qqq_2023_2024.gate.json'),
        'utf8'
    )
);

describe('X.10 gate — engine total return vs independent references', () => {
    const input: BacktestInput = {
        budget: 10_000,
        holdings: [{ label: fixture.label, weightPct: 100, drip: true }],
        seriesByLabel: { [fixture.label]: fixture.series },
        range: { from: fixture.from, to: fixture.to },
        seed: 1,
        riskFreeRate: 0.043,
    };
    const result = runBacktest(input);

    it('matches the Python DRIP reimplementation within 0.5pp', () => {
        expect(
            Math.abs(result.metrics.totalReturnPct - fixture.expected.pyDrip)
        ).toBeLessThan(0.005);
    });

    it('matches yfinance Adj Close total return within 1pp', () => {
        if (fixture.expected.yfAdjClose === undefined) return;
        expect(
            Math.abs(
                result.metrics.totalReturnPct - fixture.expected.yfAdjClose
            )
        ).toBeLessThan(0.01);
    });
});
