// Purpose: produce a one-time signed upload URL for a post image via the
//          Supabase Storage REST API (Option B: native fetch, no supabase-js).
// Invariants:
//   * contentType MUST be in the image allowlist; otherwise the call is rejected
//     before any network I/O.
//   * The storage path is namespaced by userId (`${userId}/...`) so an author can
//     only ever write under their own prefix.
//   * The uniqueness token is an explicit ARGUMENT — this module performs no
//     Date.now()/Math.random itself, keeping path derivation deterministic. The
//     impure suffix is generated by the route handler.
// Side effects: a single network POST to Supabase Storage to mint the signed URL.
const ALLOWED_IMAGE_TYPES: Record<string, string> = {
    'image/png': 'png',
    'image/jpeg': 'jpg',
    'image/webp': 'webp',
    'image/gif': 'gif',
};

export type TSignImageUploadConfig = {
    supabaseUrl: string;
    secretKey: string;
    publicBase: string;
    bucket: string;
};

export type TSignImageUploadInput = {
    userId: number;
    filename: string;
    contentType: string;
    uniqueSuffix: string;
};

export type TSignImageUploadResult =
    | {
          ok: true;
          value: { signedUrl: string; path: string; publicUrl: string };
      }
    | { ok: false; reason: string };

function extFor(contentType: string): string | null {
    return ALLOWED_IMAGE_TYPES[contentType] ?? null;
}

export function buildImagePath(
    userId: number,
    filename: string,
    uniqueSuffix: string,
    ext: string
): string {
    const base = filename
        .toLowerCase()
        .replace(/\.[^.]+$/, '')
        .replace(/[^a-z0-9-]/g, '-')
        .replace(/-+/g, '-')
        .replace(/^-+|-+$/g, '')
        .slice(0, 40);
    const name = base || 'image';
    return `${userId}/${name}-${uniqueSuffix}.${ext}`;
}

export async function signImageUpload(
    config: TSignImageUploadConfig,
    input: TSignImageUploadInput
): Promise<TSignImageUploadResult> {
    const ext = extFor(input.contentType);
    if (!ext) {
        return { ok: false, reason: 'unsupported content type' };
    }

    const path = buildImagePath(
        input.userId,
        input.filename,
        input.uniqueSuffix,
        ext
    );

    const endpoint = `${config.supabaseUrl}/storage/v1/object/upload/sign/${config.bucket}/${path}`;
    const response = await fetch(endpoint, {
        method: 'POST',
        headers: {
            Authorization: `Bearer ${config.secretKey}`,
            'Content-Type': 'application/json',
        },
    });

    if (!response.ok) {
        return { ok: false, reason: `storage sign failed (${response.status})` };
    }

    const body = (await response.json()) as { url?: string };
    const signedPath = body.url;
    if (!signedPath) {
        return { ok: false, reason: 'storage returned no signed url' };
    }

    const signedUrl = `${config.supabaseUrl}/storage/v1${signedPath}`;
    const publicUrl = `${config.publicBase}/${config.bucket}/${path}`;

    return { ok: true, value: { signedUrl, path, publicUrl } };
}
