import { ETreeNodeType, TTreeNode } from '@repo/types';

// Example flat data structure
export const flatCategoryData: TTreeNode[] = [
    {
        type: ETreeNodeType.CATEGORY,
        id: '1001',
        parent_id: null,
        level: 0,
        group_id: '1001',
        priority: 100,
        title: 'java',
        post_id: null,
        slug: null,
        description: null,
        created_at: null,
        updated_at: null,
        sort_key: '1',
        username: 'taeklim',
    },
    {
        type: ETreeNodeType.CATEGORY,
        id: '1002',
        parent_id: '1001',
        level: 1,
        group_id: '1001',
        priority: 100,
        title: 'spring',
        post_id: null,
        slug: null,
        description: null,
        created_at: null,
        updated_at: null,
        sort_key: '2',
        username: 'taeklim',
    },
    {
        type: ETreeNodeType.CATEGORY,
        id: '1003',
        parent_id: '1002',
        level: 2,
        group_id: '1001',
        priority: 100,
        title: 'jdbc',
        post_id: null,
        slug: null,
        description: null,
        created_at: null,
        updated_at: null,
        sort_key: '3',
        username: 'taeklim',
    },
    {
        type: ETreeNodeType.POST,
        id: '2001',
        parent_id: '1003',
        level: 3,
        group_id: null,
        priority: 100,
        title: 'java spring jdbc',
        post_id: '2001',
        slug: 'java-spring-jdbc',
        description: null,
        created_at: '2025-11-06T01:23:56.765Z',
        updated_at: '2025-11-06T01:23:56.765Z',
        sort_key: '4',
        username: 'taeklim',
    },
    {
        type: ETreeNodeType.CATEGORY,
        id: '1004',
        parent_id: null,
        level: 0,
        group_id: '1004',
        priority: 100,
        title: 'javascript',
        post_id: null,
        slug: null,
        description: null,
        created_at: null,
        updated_at: null,
        sort_key: '5',
        username: 'taeklim',
    },
    {
        type: ETreeNodeType.CATEGORY,
        id: '1005',
        parent_id: '1004',
        level: 1,
        group_id: '1004',
        priority: 100,
        title: 'react',
        post_id: null,
        slug: null,
        description: null,
        created_at: null,
        updated_at: null,
        sort_key: '6',
        username: 'taeklim',
    },
    {
        type: ETreeNodeType.POST,
        id: '2002',
        parent_id: '1005',
        level: 2,
        group_id: null,
        priority: 100,
        title: 'React Hooks Guide',
        post_id: '2002',
        slug: 'react-hooks-guide',
        description: null,
        created_at: '2025-11-06T02:00:00.000Z',
        updated_at: '2025-11-06T02:00:00.000Z',
        sort_key: '7',
        username: 'taeklim',
    },
];
