-- =============================================================================
-- Migration: 0001_blog_schema.sql
-- Purpose   : Create all tables for the tradelunch blog schema.
-- Source    : apps/dashboard_server/schema/tradelunch.schema.sql (authoritative)
-- Note      : Pure DDL. Seed data is in supabase/seed.sql.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- ENUM TYPES
-- Postgres does not support CREATE TYPE IF NOT EXISTS — use DO block guard.
-- ---------------------------------------------------------------------------
DO $$ BEGIN
    CREATE TYPE users_auth_provider AS ENUM (
        'app',
        'facebook',
        'google',
        'github',
        'kakao',
        'naver',
        'apple',
        'twitter',
        'linkedin',
        'microsoft',
        'yahoo'
    );
EXCEPTION WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE post_status_enum AS ENUM ('public', 'private', 'follower');
EXCEPTION WHEN duplicate_object THEN null;
END $$;

-- ---------------------------------------------------------------------------
-- USERS
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
    seq             int8 GENERATED ALWAYS AS IDENTITY(
                        INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807
                        START 1 CACHE 1 NO CYCLE
                    ) NOT NULL,
    id              BIGSERIAL PRIMARY KEY,
    username        VARCHAR(50) UNIQUE,
    email           VARCHAR(255) UNIQUE,
    password_hash   VARCHAR(255),
    provider        users_auth_provider NOT NULL DEFAULT 'app',
    provider_id     VARCHAR(255) UNIQUE,
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted_at      TIMESTAMP DEFAULT NULL
);

-- ---------------------------------------------------------------------------
-- POSTS
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS posts (
    seq             int8 GENERATED ALWAYS AS IDENTITY(
                        INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807
                        START 1 CACHE 1 NO CYCLE
                    ) NOT NULL,
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    group_id        BIGINT,
    level           INT DEFAULT 0,
    parent_id       BIGINT NULL,
    FOREIGN KEY (parent_id) REFERENCES posts(id) ON DELETE CASCADE,
    priority        INT NOT NULL DEFAULT 100,
    slug            VARCHAR(255) NOT NULL,
    title           VARCHAR(255) NOT NULL,
    content         TEXT,
    category_id     BIGINT NULL,
    user_id         BIGINT NOT NULL,
    description     TEXT DEFAULT NULL,
    meta_title      VARCHAR(70) DEFAULT NULL,
    meta_description VARCHAR(170) DEFAULT NULL,
    og_image_url    TEXT DEFAULT NULL,
    og_image_alt    VARCHAR(125) DEFAULT NULL,
    status          post_status_enum NOT NULL DEFAULT 'public',
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted_at      TIMESTAMP DEFAULT NULL,
    PRIMARY KEY (id)
);

-- ---------------------------------------------------------------------------
-- CATEGORIES (self-referencing tree; group_id = root ancestor)
-- Duplicate FK categories_parent_id_fkey1 removed — keep only CASCADE variant.
-- root_id column does not exist; group_id serves that role.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS categories (
    seq             int8 GENERATED ALWAYS AS IDENTITY(
                        INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807
                        START 1 CACHE 1 NO CYCLE
                    ) NOT NULL,
    id              int8 GENERATED BY DEFAULT AS IDENTITY(
                        INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807
                        START 1 CACHE 1 NO CYCLE
                    ) NOT NULL,
    group_id        int8 NULL,
    level           int4 DEFAULT 0 NOT NULL,
    priority        int4 DEFAULT 100 NOT NULL,
    parent_id       int8 NULL,
    user_id         int8 NOT NULL,
    title           varchar(100) NOT NULL,
    created_at      timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    updated_at      timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    deleted_at      timestamp NULL,
    CONSTRAINT categories_pkey PRIMARY KEY (id),
    CONSTRAINT categories_seq_key UNIQUE (seq),
    CONSTRAINT categories_user_title_key UNIQUE (user_id, title),
    CONSTRAINT categories_parent_id_fkey FOREIGN KEY (parent_id)
        REFERENCES categories(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_categories_parent_id ON categories(parent_id);
CREATE INDEX IF NOT EXISTS idx_categories_level ON categories(level);

-- ---------------------------------------------------------------------------
-- FILES
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS files (
    seq             int8 GENERATED ALWAYS AS IDENTITY(
                        INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807
                        START 1 CACHE 1 NO CYCLE
                    ) NOT NULL,
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT,
    post_id         BIGINT,
    content_type    VARCHAR(100),
    ext             VARCHAR(30),
    original_filename   VARCHAR(255) NOT NULL,
    stored_name         VARCHAR(255) NOT NULL,
    s3_key              TEXT NULL,
    stored_uri          TEXT NOT NULL,
    file_size           INTEGER,
    is_thumbnail        BOOLEAN DEFAULT FALSE,
    created_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted_at          TIMESTAMP DEFAULT NULL,
    UNIQUE(user_id, stored_name)
);

-- ---------------------------------------------------------------------------
-- TAGS
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS tags (
    seq             int8 GENERATED ALWAYS AS IDENTITY(
                        INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807
                        START 1 CACHE 1 NO CYCLE
                    ) NOT NULL,
    id              BIGSERIAL PRIMARY KEY,
    title           VARCHAR(50) UNIQUE NOT NULL,
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted_at      TIMESTAMP DEFAULT NULL
);

CREATE INDEX IF NOT EXISTS idx_tags_title ON tags(title);

-- ---------------------------------------------------------------------------
-- POST_TAGS (many-to-many; tag_id consolidated into CREATE TABLE — no ALTER needed)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS post_tags (
    seq             int8 GENERATED ALWAYS AS IDENTITY(
                        INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807
                        START 1 CACHE 1 NO CYCLE
                    ) NOT NULL,
    post_id         BIGINT NOT NULL,
    tag_id          BIGINT NOT NULL,
    tag_title       VARCHAR(50) NOT NULL,
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted_at      TIMESTAMP DEFAULT NULL,
    PRIMARY KEY (post_id, tag_title)
);

-- ---------------------------------------------------------------------------
-- POST_CATEGORIES (many-to-many)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS post_categories (
    seq             int8 GENERATED ALWAYS AS IDENTITY(
                        INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807
                        START 1 CACHE 1 NO CYCLE
                    ) NOT NULL,
    post_id         BIGINT NOT NULL,
    category_id     BIGINT NOT NULL,
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted_at      TIMESTAMP DEFAULT NULL,
    PRIMARY KEY (post_id, category_id)
);

-- ---------------------------------------------------------------------------
-- INDEXES
-- ---------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_users_username ON users(username);
CREATE INDEX IF NOT EXISTS idx_users_provider_id ON users(provider_id);
CREATE INDEX IF NOT EXISTS idx_posts_user_id ON posts(user_id);
CREATE INDEX IF NOT EXISTS idx_files_user_id ON files(user_id);
CREATE INDEX IF NOT EXISTS idx_files_post_id ON files(post_id);
CREATE INDEX IF NOT EXISTS idx_post_tags_tag_title ON post_tags(tag_title);
CREATE INDEX IF NOT EXISTS idx_post_tags_post_id ON post_tags(post_id);
CREATE INDEX IF NOT EXISTS idx_post_categories_category_id ON post_categories(category_id);
CREATE INDEX IF NOT EXISTS idx_post_categories_post_id ON post_categories(post_id);

-- Performance composite indexes
CREATE INDEX IF NOT EXISTS idx_posts_user_deleted_id
    ON posts(user_id, deleted_at, id DESC)
    WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_posts_slug_created
    ON posts(slug, created_at DESC, id DESC)
    WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_files_post_thumbnail
    ON files(post_id, is_thumbnail)
    WHERE deleted_at IS NULL AND is_thumbnail = true;
