-- =============================================================================
-- Migration: 0003_clerk_multiuser.sql
-- Purpose   : Bridge Clerk identity onto the existing users table and add an
--             invite-only signup gate (invites table). Phase D, step D0.
-- Style     : Additive-only, idempotent, rollback-safe. No destructive ops
--             (no DROP, no column type changes, no NOT NULL backfills).
-- Source    : apps/dashboard_server/schema/tradelunch.schema.sql (authoritative)
-- Invariants:
--   * Do NOT replace the integer users.id PK — Clerk id is a secondary lookup
--     key (clerk_user_id TEXT), the BIGSERIAL id stays the canonical FK target.
--   * Do NOT add UNIQUE(user_id, slug) on posts — would break the versioned-slug
--     CTE that relies on duplicate slugs across post revisions.
--   * Do NOT add a `published` boolean — post_status_enum is the single
--     visibility axis ('public' | 'private' | 'follower').
-- =============================================================================

-- ---------------------------------------------------------------------------
-- USERS: Clerk bridge columns (additive)
-- ---------------------------------------------------------------------------
ALTER TABLE users ADD COLUMN IF NOT EXISTS clerk_user_id TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS display_name  VARCHAR(100);
ALTER TABLE users ADD COLUMN IF NOT EXISTS avatar_url    TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS is_admin      BOOLEAN NOT NULL DEFAULT false;

-- UNIQUE on clerk_user_id. ADD CONSTRAINT has no IF NOT EXISTS — guard with a
-- duplicate_object catch so re-runs are no-ops.
DO $$ BEGIN
    ALTER TABLE users ADD CONSTRAINT users_clerk_user_id_key UNIQUE (clerk_user_id);
EXCEPTION WHEN duplicate_object THEN null;
END $$;

CREATE INDEX IF NOT EXISTS idx_users_clerk_user_id ON users(clerk_user_id);

-- ---------------------------------------------------------------------------
-- POSTS: FK hardening on user_id (additive)
-- posts.user_id previously had only an index (idx_posts_user_id), no FK.
-- Guarded so a re-run (or a future schema that already declares the FK) is safe.
-- ---------------------------------------------------------------------------
DO $$ BEGIN
    ALTER TABLE posts ADD CONSTRAINT posts_user_id_fkey
        FOREIGN KEY (user_id) REFERENCES users(id);
EXCEPTION WHEN duplicate_object THEN null;
END $$;

-- ---------------------------------------------------------------------------
-- INVITES: invite-only signup gate
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS invites (
    seq             int8 GENERATED ALWAYS AS IDENTITY(
                        INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807
                        START 1 CACHE 1 NO CYCLE
                    ) NOT NULL,
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code            VARCHAR(64) NOT NULL UNIQUE,
    email           VARCHAR(255) DEFAULT NULL,
    created_by      BIGINT REFERENCES users(id),
    used_by         BIGINT REFERENCES users(id) DEFAULT NULL,
    used_at         TIMESTAMP DEFAULT NULL,
    expires_at      TIMESTAMP DEFAULT NULL,
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted_at      TIMESTAMP DEFAULT NULL
);

CREATE INDEX IF NOT EXISTS idx_invites_code ON invites(code) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_invites_used_by ON invites(used_by);
