-- =============================================================================
-- Migration: 0014_error_logs.sql
-- Purpose   : Operational sink for browser / SSR error-boundary reports. The
--             Next runtime forwards each caught render error (digest + message +
--             stack + path + user_agent) server-to-server to Express, which is
--             the sole Supabase owner; the Next SSR server has NO DB access by
--             design. This table is the landing spot for that ingest so prod
--             `digest`-only boundary output can be resolved back to a real stack.
-- Note      : MANUAL — apply by hand AFTER 0013. Additive + idempotent.
--             Re-confirm next free number before applying (multi-session).
-- EXCEPTION : This is an OPERATIONAL LOG and is an explicit, owner-approved
--             EXCEPTION to the repo soft-delete rule. There is intentionally NO
--             `deleted_at` column — rows are HARD-deleted by a TTL cleanup (see
--             the commented pg_cron block at the bottom), not tombstoned. Do not
--             "fix" this by adding a soft-delete column.
-- =============================================================================

CREATE TABLE IF NOT EXISTS error_log (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    digest      TEXT NULL,                              -- Next prod error digest (log-correlation key)
    message     TEXT NULL,
    stack       TEXT NULL,
    path        TEXT NULL,                              -- window.location.pathname at failure
    user_agent  TEXT NULL,
    source      TEXT NOT NULL DEFAULT 'browser',        -- 'browser' | 'ssr' | future origins
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- TTL cleanup scans by age, so created_at is the sole filter column.
CREATE INDEX IF NOT EXISTS idx_error_log_created_at ON error_log(created_at);

-- -----------------------------------------------------------------------------
-- TTL cleanup (HARD delete) — pg_cron. Kept COMMENTED OUT so the table DDL above
-- applies cleanly even on a project where the pg_cron extension is not enabled.
-- Enabling pg_cron is a Supabase-dashboard / USER action (Database → Extensions).
-- Runs daily at 03:00 UTC; pg_cron schedules are evaluated in UTC.
-- -----------------------------------------------------------------------------
-- SELECT cron.schedule(
--     'error_log_cleanup',
--     '0 3 * * *',
--     $$ DELETE FROM error_log WHERE created_at < now() - interval '7 days' $$
-- );
