-- =============================================================================
-- Migration: 0015_batch_log.sql
-- Purpose   : Operational sink for collector batch runs (GitHub Actions cron).
--             Each run of run_daily / run_weekly appends ONE row recording the
--             outcome, so "did last night's job run, and how did it go?" is a
--             single SQL query instead of digging through Actions run history.
-- Note      : MANUAL — apply by hand AFTER 0014. Additive + idempotent.
--             Re-confirm next free number before applying (multi-session).
-- EXCEPTION : This is an OPERATIONAL LOG and is an explicit, owner-approved
--             EXCEPTION to the repo soft-delete rule — like error_log (0014).
--             There is intentionally NO `deleted_at`; prune with a TTL if needed.
-- WRITER    : apps/stock_collector writes here best-effort — a missing table or
--             insert error never fails the collection job (graceful degrade).
-- =============================================================================

CREATE TABLE IF NOT EXISTS batch_log (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job          TEXT NOT NULL,                          -- 'collector-daily' | 'collector-weekly'
    status       TEXT NOT NULL,                          -- 'success' | 'failed'
    resolved     SMALLINT NOT NULL DEFAULT 0,            -- success=1, failed=0 (open-failure tracker)
    started_at   TIMESTAMPTZ NOT NULL,
    finished_at  TIMESTAMPTZ NULL,
    descr        TEXT NULL,                              -- pipe-separated, e.g. "ok=40|fail=2|history=312|snapshots=42"
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Open-failure lookup: WHERE resolved = 0 ORDER BY started_at DESC.
CREATE INDEX IF NOT EXISTS idx_batch_log_resolved_started
    ON batch_log(resolved, started_at);

-- Per-job history lookup.
CREATE INDEX IF NOT EXISTS idx_batch_log_job_started
    ON batch_log(job, started_at);
