# database schema
-- ===========================
-- USERS TABLE
-- ===========================
CREATE TYPE if not exists users_auth_provider AS ENUM (
    'app',
    'facebook',
    'google',
    'github',
    'kakao',
    'naver',
    'apple',
    'twitter',
    'linkedin',
    'microsoft',
    'yahoo',
);

drop table if exists users;
CREATE TABLE if not exists users (
    seq int8 GENERATED ALWAYS AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    id              BIGSERIAL PRIMARY KEY,
    username        VARCHAR(50) UNIQUE,
    email           VARCHAR(255) UNIQUE,
    password_hash   VARCHAR(255), -- nullable
    provider        users_auth_provider NOT NULL DEFAULT 'app', -- ex: google, github, apple
    provider_id     VARCHAR(255) UNIQUE, -- external id from oauth
    -- Phase D: Clerk identity bridge (clerk_user_id is a secondary key; id PK stays canonical)
    clerk_user_id   TEXT UNIQUE,
    display_name    VARCHAR(100),
    avatar_url      TEXT,
    is_admin        BOOLEAN NOT NULL DEFAULT false,
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted_at      TIMESTAMP DEFAULT NULL
);

insert into users (username, email)
VALUES ('darkowlrising', 'darkowlrising@gmail.com');
insert into users (username, email)
VALUES ('taeklim', 'tio.taek.lim@gmail.com');


-- ===========================
-- POSTS TABLE
-- ===========================
CREATE TYPE if not exists post_status_enum AS ENUM ('public', 'private', 'follower', 'draft');
drop table if exists posts;
CREATE TABLE posts (
    seq             int8 GENERATED ALWAYS AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    -- id              BIGSERIAL PRIMARY KEY,
    -- id              BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    -- id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    group_id        BIGINT,                         -- 루트 글 ID (root면 자기 자신)
    level           INT DEFAULT 0,                  -- 깊이 (root = 0)
    parent_id       BIGINT NULL,                    -- 부모 글 ID
    FOREIGN KEY (parent_id) REFERENCES posts(id) on delete cascade,
    -- --
    priority        INT NOT NULL DEFAULT 100,
    -- reply_count     INT DEFAULT 0,                  -- 자식 글 수
    slug            VARCHAR(255) NOT NULL,
    title           VARCHAR(255) NOT NULL,
    content         TEXT,
    category_id     BIGINT NULL,
    user_id         BIGINT NOT NULL,
    -- Phase D: FK hardening — user_id references users(id)
    CONSTRAINT posts_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id),
    description     TEXT DEFAULT NULL,
    -- SEO fields
    meta_title      VARCHAR(70) DEFAULT NULL,
    meta_description VARCHAR(170) DEFAULT NULL,
    og_image_url    TEXT DEFAULT NULL,
    og_image_alt    VARCHAR(125) DEFAULT NULL,
    -- --
    status          post_status_enum NOT NULL DEFAULT 'public',
    -- --
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted_at      TIMESTAMP DEFAULT NULL,
    PRIMARY KEY (id)
);

--> just in case to update colums
-- ALTER TABLE posts ADD COLUMN meta_title VARCHAR(70);
-- ALTER TABLE posts ADD COLUMN meta_description VARCHAR(170);
-- ALTER TABLE posts ADD COLUMN og_image_url TEXT;
-- ALTER TABLE posts ADD COLUMN og_image_alt VARCHAR(125);



-- ===========================
-- categories TABLE
-- ===========================
-- CREATE TABLE categories (
--     id          BIGSERIAL PRIMARY KEY,
--     name        VARCHAR(100) NOT NULL,
--     parent_id   BIGINT REFERENCES categories(id) ON DELETE CASCADE,
--     root_id     BIGINT NOT NULL REFERENCES categories(id) ON DELETE CASCADE,
--     level       INT NOT NULL DEFAULT 0,
--     UNIQUE(name, parent_id)
-- );

-- drop table if exists categories;
-- CREATE TABLE if not exists categories (
--     id              BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
--     name        VARCHAR(100) NOT NULL, --UNIQUE,
--     parent_id   BIGINT NOT NULL,
--     root_id     BIGINT NOT NULL,
--     level       INT NOT NULL DEFAULT 0,
--     created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--     updated_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--     deleted_at      TIMESTAMP DEFAULT NULL
-- );

CREATE TABLE if not exists categories (
    seq int8 GENERATED ALWAYS AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    group_id int8 NULL,
    "level" int4 DEFAULT 0 NOT NULL,
    priority int4 DEFAULT 100 NOT NULL,
    parent_id int8 NULL,
    user_id int8 NOT NULL,
    title varchar(100) NOT NULL,
    created_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    updated_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    deleted_at timestamp NULL, CONSTRAINT categories_pkey
    PRIMARY KEY (id),
    CONSTRAINT categories_seq_key UNIQUE (seq),
    CONSTRAINT categories_user_title_key UNIQUE (user_id, title),
    CONSTRAINT categories_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.categories(id) ON DELETE CASCADE,
    CONSTRAINT categories_parent_id_fkey1 FOREIGN KEY (parent_id) REFERENCES public.categories(id)
);

-- 인덱스
CREATE INDEX if not exists idx_categories_parent_id ON categories(parent_id);
CREATE INDEX if not exists idx_categories_root_id ON categories(root_id);
CREATE INDEX if not exists idx_categories_level ON categories(level);


-- ===========================
-- FILES TABLE
-- ===========================
-- Maps to MCPFileInfo in schema.py:
--   original_filename: Original filename from local filesystem
--   stored_name: Slug-based filename for storage (e.g., "article-slug.png")
--   s3_key: Full S3 key path (e.g., "4/tech/ai/article-slug/article-slug.png")
--   s3_url: Full CDN URL (stored_uri alias)
--   content_type: MIME type
--   ext: File extension without dot
--   file_size: Size in bytes
--   is_thumbnail: Whether this is the post thumbnail
drop table if exists files;
CREATE TABLE if not exists files (
    seq int8 GENERATED ALWAYS AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT,
    post_id         BIGINT,
    content_type    VARCHAR(100),
    ext             VARCHAR(30),
    original_filename   VARCHAR(255) NOT NULL,
    stored_name         VARCHAR(255) NOT NULL,
    s3_key              TEXT NULL,              -- S3 key path (e.g., "user_id/category/.../slug/filename")
    stored_uri          TEXT NOT NULL,          -- Full CDN URL (s3_url)
    file_size           INTEGER,
    is_thumbnail        BOOLEAN DEFAULT FALSE,
    created_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted_at          TIMESTAMP DEFAULT NULL,
    UNIQUE(user_id, stored_name)
);

-- ===========================
-- TAGS TABLE
-- ===========================
CREATE TABLE if not exists tags (
    seq int8 GENERATED ALWAYS AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    id              BIGSERIAL PRIMARY KEY,
    title           VARCHAR(50) UNIQUE NOT NULL,
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted_at      TIMESTAMP DEFAULT NULL
);
CREATE INDEX if not exists idx_tags_title ON tags(title);

-- ===========================
-- POST_TAGS (many-to-many)
-- ===========================
drop table if exists post_tags;
CREATE TABLE if not exists post_tags (
    seq int8 GENERATED ALWAYS AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    post_id         BIGINT NOT NULL,
    tag_id          BIGINT NOT NULL,
    tag_title       VARCHAR(50) NOT NULL,
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted_at      TIMESTAMP DEFAULT NULL,
    PRIMARY KEY (post_id, tag_title)
);

-- 1. Drop the UNIQUE constraint on tag_title
ALTER TABLE post_tags DROP CONSTRAINT IF EXISTS post_tags_tag_title_key;
-- 2. Add tag_id column
ALTER TABLE post_tags ADD COLUMN tag_id BIGINT;
-- Optional: If you want to make tag_id NOT NULL after populating existing rows
UPDATE post_tags pt SET tag_id = t.id FROM tags t WHERE pt.tag_title = t.title;
ALTER TABLE post_tags ALTER COLUMN tag_id SET NOT NULL;

-- ===========================
-- INDEXES
-- ===========================
CREATE INDEX if not exists idx_users_username ON users(username);
CREATE INDEX if not exists idx_users_provider_id ON users(provider_id);
CREATE INDEX if not exists idx_users_clerk_user_id ON users(clerk_user_id);
CREATE INDEX if not exists idx_posts_user_id ON posts(user_id);
CREATE INDEX if not exists idx_files_user_id ON files(user_id);
CREATE INDEX if not exists idx_files_post_id ON files(post_id);
CREATE INDEX if not exists idx_post_tags_tag_title ON post_tags(tag_title);
CREATE INDEX if not exists idx_post_tags_post_id ON post_tags(post_id);


-- ===========================
-- post_categories TABLE
-- ===========================
-- CREATE TABLE post_categories (
--     post_id     BIGINT NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
--     category_id BIGINT NOT NULL REFERENCES categories(id) ON DELETE CASCADE,
--     PRIMARY KEY (post_id, category_id)
-- );
CREATE TABLE if not exists post_categories (
    seq int8 GENERATED ALWAYS AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    post_id     BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted_at      TIMESTAMP DEFAULT NULL,
    PRIMARY KEY (post_id, category_id)
);

CREATE INDEX if not exists idx_post_categories_category_id ON post_categories(category_id);
CREATE INDEX if not exists idx_post_categories_post_id ON post_categories(post_id);


-- ===========================
-- INVITES TABLE (Phase D: invite-only signup gate)
-- ===========================
CREATE TABLE if not exists invites (
    seq int8 GENERATED ALWAYS AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code            VARCHAR(64) NOT NULL UNIQUE,
    email           VARCHAR(255) DEFAULT NULL,
    created_by      BIGINT REFERENCES users(id),
    used_by         BIGINT REFERENCES users(id) DEFAULT NULL,
    used_at         TIMESTAMP DEFAULT NULL,
    expires_at      TIMESTAMP DEFAULT NULL,
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted_at      TIMESTAMP DEFAULT NULL
);

CREATE INDEX if not exists idx_invites_code ON invites(code) WHERE deleted_at IS NULL;
CREATE INDEX if not exists idx_invites_used_by ON invites(used_by);


-- ===========================
-- upsert
-- ===========================

INSERT INTO users (username, email, password_hash)
VALUES ('john', 'john@example.com', 'hashed_pw')
ON CONFLICT (email)
DO UPDATE
SET username = EXCLUDED.username,
    password_hash = EXCLUDED.password_hash,
    updated_at = CURRENT_TIMESTAMP;

INSERT INTO users (username, email)
VALUES ('john', 'john@example.com')
ON CONFLICT (email)
DO NOTHING;


-- 복합 인덱스 추가로 성능 극대화
CREATE INDEX IF NOT EXISTS idx_posts_user_deleted_id
ON posts(user_id, deleted_at, id DESC)
WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_posts_slug_created
ON posts(slug, created_at DESC, id DESC)
WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_files_post_thumbnail
ON files(post_id, is_thumbnail)
WHERE deleted_at IS NULL AND is_thumbnail = true;

-- ===========================
-- MARKET DASHBOARD TABLES
-- Backs the financial dashboard endpoints (/v1/api/dashboard/*).
-- Contract: dashboard_client_web/types/dashboard.ts + types/history.ts
-- ===========================

-- market_snapshots: one row per dashboard item; covers IDashboardItem /
-- IStockItem (value + change) + ICategoryMeta (as_of, revalidate_seconds) +
-- snapshot fetched_at.
CREATE TABLE if not exists market_snapshots (
    seq int8 GENERATED ALWAYS AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    category            TEXT NOT NULL,
    label               TEXT NOT NULL,
    ticker              TEXT NULL,
    exchange            TEXT NULL,
    value               NUMERIC NOT NULL,
    change_absolute     NUMERIC NOT NULL,
    change_percent      NUMERIC NOT NULL,
    as_of               TIMESTAMPTZ NOT NULL,
    revalidate_seconds  INT NOT NULL,
    fetched_at          TIMESTAMPTZ NOT NULL,
    created_at          TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT market_snapshots_category_check CHECK (category IN ('fx', 'crypto', 'indices', 'rates', 'stocks')),
    CONSTRAINT market_snapshots_pkey PRIMARY KEY (category, label)
);

CREATE INDEX IF NOT EXISTS idx_market_snapshots_category ON market_snapshots(category);

-- market_history: one OHLC candle per item per interval; covers IOHLCPoint
-- grouped by label -> IItemOHLCHistory.
CREATE TABLE if not exists market_history (
    seq int8 GENERATED ALWAYS AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    label       TEXT NOT NULL,
    interval    TEXT NOT NULL,
    bar_time    TIMESTAMPTZ NOT NULL,
    open        NUMERIC NOT NULL,
    high        NUMERIC NOT NULL,
    low         NUMERIC NOT NULL,
    close       NUMERIC NOT NULL,
    volume      BIGINT NOT NULL,
    created_at  TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT market_history_pkey PRIMARY KEY (label, interval, bar_time)
);

CREATE INDEX IF NOT EXISTS idx_market_history_label_interval ON market_history(label, interval, bar_time);


-- ===========================
-- POST_FAVORITES TABLE
-- Per-user blog post favorites (Phase 2 — post-card Save persistence).
-- Composite PK (user_id, post_id) dedupes; insert uses ON CONFLICT DO NOTHING.
-- post_id is a Snowflake BIGINT — read as a STRING end-to-end.
-- ===========================
CREATE TABLE IF NOT EXISTS post_favorites (
    user_id     BIGINT NOT NULL REFERENCES users(id),
    post_id     BIGINT NOT NULL REFERENCES posts(id),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id, post_id)
);

CREATE INDEX IF NOT EXISTS idx_post_favorites_user ON post_favorites(user_id);

-- 0007: index the saved-posts list order (user_id + created_at DESC).
-- Additive; the existing idx_post_favorites_user (user_id) is KEPT.
CREATE INDEX IF NOT EXISTS idx_post_favorites_user_created
    ON post_favorites (user_id, created_at DESC);


-- ===========================
-- POST_LIKES TABLE
-- Per-user blog post LIKES (Phase E — public like count). A like is a PUBLIC
-- approval signal: aggregate COUNT(*) visible to everyone + a per-viewer
-- "did I like this" boolean. Distinct from post_favorites (private bookmark).
-- Composite PK (user_id, post_id) dedupes; insert uses ON CONFLICT DO NOTHING.
-- post_id is a Snowflake BIGINT — read as a STRING end-to-end.
-- Like count is a LIVE COUNT(*) (no denormalized counter), served by
-- idx_post_likes_post. FK ON DELETE: NO ACTION, matching post_favorites for
-- cross-table consistency (db-structure-audit Issue #3).
-- ===========================
CREATE TABLE IF NOT EXISTS post_likes (
    user_id     BIGINT NOT NULL REFERENCES users(id),
    post_id     BIGINT NOT NULL REFERENCES posts(id),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id, post_id)
);

CREATE INDEX IF NOT EXISTS idx_post_likes_post ON post_likes(post_id);


-- ===========================
-- COMMENTS TABLE
-- Threaded reader comments on blog posts (Phase E — Option C). Adjacency-list
-- (parent_id, immutable) PLUS a stored self-inclusive BIGINT[] materialized
-- `path` (path = parent.path || id). The path is the single WRITE-ONCE sort
-- key: WHERE post_id=$1 ORDER BY path yields the whole thread in pre-order DFS
-- with NO WITH RECURSIVE, no zero-padding, no extension. Depth is UNLIMITED
-- (derived cardinality(path)-1, never enforced; client render-collapses).
-- PARALLEL to apps/blog_agent's posts-based tree — does NOT touch
-- posts.parent_id/group_id/level. comments.parent_id self-refs comments(id),
-- NEVER posts. ids are Snowflake BIGINT IDENTITY, read as STRINGS end-to-end.
-- Soft-delete via deleted_at (tombstone, masked at READ — original retained).
-- FK ON DELETE: NO ACTION, matching post_favorites / post_likes for cross-table
-- consistency (db-structure-audit Issue #3).
-- ===========================
CREATE TABLE IF NOT EXISTS comments (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id     BIGINT NOT NULL REFERENCES posts(id),
    user_id     BIGINT NOT NULL REFERENCES users(id),
    parent_id   BIGINT NULL     REFERENCES comments(id),
    path        BIGINT[] NOT NULL,
    body        TEXT NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at  TIMESTAMPTZ NULL
);

CREATE INDEX IF NOT EXISTS idx_comments_post_path ON comments(post_id, path);
CREATE INDEX IF NOT EXISTS idx_comments_parent ON comments(parent_id);

-- =============================================================================
-- Phase I (Phase 2): sticky universe + weekly market-cap ranking series.
-- Mirrors migrations 0011_tracked_symbols.sql + 0012_market_rankings.sql.
-- =============================================================================

-- tracked_symbols: STICKY universe — once ranked, collected forever. Soft-delete
-- (deleted_at) only, manual admin only; weekly re-rank revives via ON CONFLICT.
-- label is UNIQUE (protects the global market_history label namespace).
CREATE TABLE IF NOT EXISTS tracked_symbols (
    symbol          TEXT NOT NULL,
    category        TEXT NOT NULL,
    label           TEXT NOT NULL,
    sector          TEXT NULL,
    source          TEXT NOT NULL DEFAULT 'yahoo',
    exchange        TEXT NULL,
    first_ranked_at TIMESTAMPTZ NULL,
    last_ranked_at  TIMESTAMPTZ NULL,
    created_at      TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    deleted_at      TIMESTAMPTZ NULL,
    CONSTRAINT tracked_symbols_pkey PRIMARY KEY (symbol),
    CONSTRAINT tracked_symbols_label_key UNIQUE (label),
    CONSTRAINT tracked_symbols_category_check CHECK (category IN ('fx', 'crypto', 'indices', 'rates', 'stocks'))
);
CREATE INDEX IF NOT EXISTS idx_tracked_symbols_category ON tracked_symbols(category) WHERE deleted_at IS NULL;

-- market_rankings: append-only weekly time series; ALL tracked symbols per week.
-- scope = 'global' (top-20) or 'sector' (top-10). Idempotent per (as_of,symbol,scope).
CREATE TABLE IF NOT EXISTS market_rankings (
    as_of       DATE NOT NULL,
    symbol      TEXT NOT NULL,
    scope       TEXT NOT NULL,
    sector      TEXT NULL,
    rank        INT NOT NULL,
    market_cap  NUMERIC NULL,
    created_at  TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT market_rankings_pkey PRIMARY KEY (as_of, symbol, scope),
    CONSTRAINT market_rankings_scope_check CHECK (scope IN ('global', 'sector'))
);
CREATE INDEX IF NOT EXISTS idx_market_rankings_asof_scope ON market_rankings(as_of, scope, rank);

-- =============================================================================
-- Phase I (I2.8): per-symbol fundamentals cache (shares + sector).
-- Mirrors migration 0013_symbol_fundamentals.sql.
-- =============================================================================

-- symbol_fundamentals: caches shares_outstanding (monthly fast_info refresh) and
-- sector (quarterly .info refresh) so the weekly rank derives market_cap =
-- shares x local close WITHOUT a per-symbol .info call. market_cap is NOT stored
-- (derived fresh each week from market_history). Soft-delete (deleted_at) only.
CREATE TABLE IF NOT EXISTS symbol_fundamentals (
    symbol              TEXT NOT NULL,
    shares_outstanding  NUMERIC NULL,
    sector              TEXT NULL,
    shares_refreshed_at TIMESTAMPTZ NULL,
    sector_refreshed_at TIMESTAMPTZ NULL,
    source              TEXT NOT NULL DEFAULT 'yahoo',
    created_at          TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    deleted_at          TIMESTAMPTZ NULL,
    CONSTRAINT symbol_fundamentals_pkey PRIMARY KEY (symbol)
);
