-- =============================================================================
-- Migration: 0009_comments.sql
-- Purpose   : Threaded reader comments on blog posts (Phase E — Option C).
--             Adjacency-list (parent_id, immutable) PLUS a stored self-inclusive
--             BIGINT[] materialized `path` (path = parent.path || id). The path
--             is the single WRITE-ONCE sort key: a plain
--             `WHERE post_id=$1 ORDER BY path` yields the whole thread in
--             pre-order DFS with NO `WITH RECURSIVE`, no zero-padding, and no
--             Postgres extension. Depth is UNLIMITED (derived as
--             cardinality(path)-1, never enforced; the client render-collapses).
-- Source    : apps/dashboard_server/schema/tradelunch.schema.sql (authoritative,
--             mirrored byte-identical in apps/blog_agent/schema/).
-- Contract  : @repo/types (TComment, TCommentListResponse, TCommentCreateRequest).
-- Note      : Additive + idempotent. PARALLEL to apps/blog_agent's posts-based
--             tree — this migration does NOT touch posts.parent_id/group_id/level
--             (those stay live for agent root-bookkeeping); comments.parent_id
--             self-references comments(id), NEVER posts. ids are Snowflake-style
--             BIGINT IDENTITY, read as STRINGS end-to-end. Soft-delete via
--             deleted_at (tombstone, masked at READ — original body retained).
--             FK ON DELETE: NO ACTION (no ON DELETE clause), matching
--             post_favorites / post_likes for cross-table consistency
--             (db-structure-audit Issue #3). The app soft-deletes, never hard
--             DELETE, so rows are not orphaned in practice.
-- =============================================================================

CREATE TABLE IF NOT EXISTS comments (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id     BIGINT NOT NULL REFERENCES posts(id),
    user_id     BIGINT NOT NULL REFERENCES users(id),
    parent_id   BIGINT NULL     REFERENCES comments(id),  -- self-ref; NULL = top-level
    path        BIGINT[] NOT NULL,                        -- self-inclusive: parent.path || id
    body        TEXT NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at  TIMESTAMPTZ NULL                          -- soft-delete tombstone (masked at READ)
);

-- Pre-order DFS read: WHERE post_id=$1 ORDER BY path (element-wise BIGINT[] sort).
CREATE INDEX IF NOT EXISTS idx_comments_post_path ON comments(post_id, path);
-- Parent / cascade lookups.
CREATE INDEX IF NOT EXISTS idx_comments_parent ON comments(parent_id);
