# database schema
-- ===========================
-- USERS TABLE
-- ===========================
CREATE TYPE if not exists users_auth_provider AS ENUM (
    'app',
    'facebook',
    'google',
    'github',
    'kakao',
    'naver',
    'apple',
    'twitter',
    'linkedin',
    'microsoft',
    'yahoo',
);

drop table if exists users;
CREATE TABLE if not exists users (
    seq int8 GENERATED ALWAYS AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    id              BIGSERIAL PRIMARY KEY,
    username        VARCHAR(50) UNIQUE,
    email           VARCHAR(255) UNIQUE,
    password_hash   VARCHAR(255), -- nullable
    provider        users_auth_provider NOT NULL DEFAULT 'app', -- ex: google, github, apple
    provider_id     VARCHAR(255) UNIQUE, -- external id from oauth
    -- Phase D: Clerk identity bridge (clerk_user_id is a secondary key; id PK stays canonical)
    clerk_user_id   TEXT UNIQUE,
    display_name    VARCHAR(100),
    avatar_url      TEXT,
    is_admin        BOOLEAN NOT NULL DEFAULT false,
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted_at      TIMESTAMP DEFAULT NULL
);

insert into users (username, email)
VALUES ('darkowlrising', 'darkowlrising@gmail.com');
insert into users (username, email)
VALUES ('taeklim', 'tio.taek.lim@gmail.com');


-- ===========================
-- POSTS TABLE
-- ===========================
CREATE TYPE if not exists post_status_enum AS ENUM ('public', 'private', 'follower', 'draft');
drop table if exists posts;
CREATE TABLE posts (
    seq             int8 GENERATED ALWAYS AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    -- id              BIGSERIAL PRIMARY KEY,
    -- id              BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    -- id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    group_id        BIGINT,                         -- 루트 글 ID (root면 자기 자신)
    level           INT DEFAULT 0,                  -- 깊이 (root = 0)
    parent_id       BIGINT NULL,                    -- 부모 글 ID
    FOREIGN KEY (parent_id) REFERENCES posts(id) on delete cascade,
    -- --
    priority        INT NOT NULL DEFAULT 100,
    -- reply_count     INT DEFAULT 0,                  -- 자식 글 수
    slug            VARCHAR(255) NOT NULL,
    title           VARCHAR(255) NOT NULL,
    content         TEXT,
    category_id     BIGINT NULL,
    user_id         BIGINT NOT NULL,
    -- Phase D: FK hardening — user_id references users(id)
    CONSTRAINT posts_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id),
    description     TEXT DEFAULT NULL,
    -- SEO fields
    meta_title      VARCHAR(70) DEFAULT NULL,
    meta_description VARCHAR(170) DEFAULT NULL,
    og_image_url    TEXT DEFAULT NULL,
    og_image_alt    VARCHAR(125) DEFAULT NULL,
    -- --
    status          post_status_enum NOT NULL DEFAULT 'public',
    -- --
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted_at      TIMESTAMP DEFAULT NULL,
    PRIMARY KEY (id)
);

--> just in case to update colums
-- ALTER TABLE posts ADD COLUMN meta_title VARCHAR(70);
-- ALTER TABLE posts ADD COLUMN meta_description VARCHAR(170);
-- ALTER TABLE posts ADD COLUMN og_image_url TEXT;
-- ALTER TABLE posts ADD COLUMN og_image_alt VARCHAR(125);



-- ===========================
-- categories TABLE
-- ===========================
-- CREATE TABLE categories (
--     id          BIGSERIAL PRIMARY KEY,
--     name        VARCHAR(100) NOT NULL,
--     parent_id   BIGINT REFERENCES categories(id) ON DELETE CASCADE,
--     root_id     BIGINT NOT NULL REFERENCES categories(id) ON DELETE CASCADE,
--     level       INT NOT NULL DEFAULT 0,
--     UNIQUE(name, parent_id)
-- );

-- drop table if exists categories;
-- CREATE TABLE if not exists categories (
--     id              BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
--     name        VARCHAR(100) NOT NULL, --UNIQUE,
--     parent_id   BIGINT NOT NULL,
--     root_id     BIGINT NOT NULL,
--     level       INT NOT NULL DEFAULT 0,
--     created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--     updated_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--     deleted_at      TIMESTAMP DEFAULT NULL
-- );

CREATE TABLE if not exists categories (
    seq int8 GENERATED ALWAYS AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    group_id int8 NULL,
    "level" int4 DEFAULT 0 NOT NULL,
    priority int4 DEFAULT 100 NOT NULL,
    parent_id int8 NULL,
    user_id int8 NOT NULL,
    title varchar(100) NOT NULL,
    created_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    updated_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    deleted_at timestamp NULL, CONSTRAINT categories_pkey
    PRIMARY KEY (id),
    CONSTRAINT categories_seq_key UNIQUE (seq),
    CONSTRAINT categories_user_title_key UNIQUE (user_id, title),
    CONSTRAINT categories_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.categories(id) ON DELETE CASCADE,
    CONSTRAINT categories_parent_id_fkey1 FOREIGN KEY (parent_id) REFERENCES public.categories(id)
);

-- 인덱스
CREATE INDEX if not exists idx_categories_parent_id ON categories(parent_id);
CREATE INDEX if not exists idx_categories_root_id ON categories(root_id);
CREATE INDEX if not exists idx_categories_level ON categories(level);


-- ===========================
-- FILES TABLE
-- ===========================
-- Maps to MCPFileInfo in schema.py:
--   original_filename: Original filename from local filesystem
--   stored_name: Slug-based filename for storage (e.g., "article-slug.png")
--   s3_key: Full S3 key path (e.g., "4/tech/ai/article-slug/article-slug.png")
--   s3_url: Full CDN URL (stored_uri alias)
--   content_type: MIME type
--   ext: File extension without dot
--   file_size: Size in bytes
--   is_thumbnail: Whether this is the post thumbnail
drop table if exists files;
CREATE TABLE if not exists files (
    seq int8 GENERATED ALWAYS AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT,
    post_id         BIGINT,
    content_type    VARCHAR(100),
    ext             VARCHAR(30),
    original_filename   VARCHAR(255) NOT NULL,
    stored_name         VARCHAR(255) NOT NULL,
    s3_key              TEXT NULL,              -- S3 key path (e.g., "user_id/category/.../slug/filename")
    stored_uri          TEXT NOT NULL,          -- Full CDN URL (s3_url)
    file_size           INTEGER,
    is_thumbnail        BOOLEAN DEFAULT FALSE,
    created_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted_at          TIMESTAMP DEFAULT NULL,
    UNIQUE(user_id, stored_name)
);

-- ===========================
-- TAGS TABLE
-- ===========================
CREATE TABLE if not exists tags (
    seq int8 GENERATED ALWAYS AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    id              BIGSERIAL PRIMARY KEY,
    title           VARCHAR(50) UNIQUE NOT NULL,
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted_at      TIMESTAMP DEFAULT NULL
);
CREATE INDEX if not exists idx_tags_title ON tags(title);

-- ===========================
-- POST_TAGS (many-to-many)
-- ===========================
drop table if exists post_tags;
CREATE TABLE if not exists post_tags (
    seq int8 GENERATED ALWAYS AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    post_id         BIGINT NOT NULL,
    tag_id          BIGINT NOT NULL,
    tag_title       VARCHAR(50) NOT NULL,
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted_at      TIMESTAMP DEFAULT NULL,
    PRIMARY KEY (post_id, tag_title)
);

-- 1. Drop the UNIQUE constraint on tag_title
ALTER TABLE post_tags DROP CONSTRAINT IF EXISTS post_tags_tag_title_key;
-- 2. Add tag_id column
ALTER TABLE post_tags ADD COLUMN tag_id BIGINT;
-- Optional: If you want to make tag_id NOT NULL after populating existing rows
UPDATE post_tags pt SET tag_id = t.id FROM tags t WHERE pt.tag_title = t.title;
ALTER TABLE post_tags ALTER COLUMN tag_id SET NOT NULL;

-- ===========================
-- INDEXES
-- ===========================
CREATE INDEX if not exists idx_users_username ON users(username);
CREATE INDEX if not exists idx_users_provider_id ON users(provider_id);
CREATE INDEX if not exists idx_users_clerk_user_id ON users(clerk_user_id);
CREATE INDEX if not exists idx_posts_user_id ON posts(user_id);
CREATE INDEX if not exists idx_files_user_id ON files(user_id);
CREATE INDEX if not exists idx_files_post_id ON files(post_id);
CREATE INDEX if not exists idx_post_tags_tag_title ON post_tags(tag_title);
CREATE INDEX if not exists idx_post_tags_post_id ON post_tags(post_id);


-- ===========================
-- post_categories TABLE
-- ===========================
-- CREATE TABLE post_categories (
--     post_id     BIGINT NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
--     category_id BIGINT NOT NULL REFERENCES categories(id) ON DELETE CASCADE,
--     PRIMARY KEY (post_id, category_id)
-- );
CREATE TABLE if not exists post_categories (
    seq int8 GENERATED ALWAYS AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    post_id     BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted_at      TIMESTAMP DEFAULT NULL,
    PRIMARY KEY (post_id, category_id)
);

CREATE INDEX if not exists idx_post_categories_category_id ON post_categories(category_id);
CREATE INDEX if not exists idx_post_categories_post_id ON post_categories(post_id);


-- ===========================
-- INVITES TABLE (Phase D: invite-only signup gate)
-- ===========================
CREATE TABLE if not exists invites (
    seq int8 GENERATED ALWAYS AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code            VARCHAR(64) NOT NULL UNIQUE,
    email           VARCHAR(255) DEFAULT NULL,
    created_by      BIGINT REFERENCES users(id),
    used_by         BIGINT REFERENCES users(id) DEFAULT NULL,
    used_at         TIMESTAMP DEFAULT NULL,
    expires_at      TIMESTAMP DEFAULT NULL,
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted_at      TIMESTAMP DEFAULT NULL
);

CREATE INDEX if not exists idx_invites_code ON invites(code) WHERE deleted_at IS NULL;
CREATE INDEX if not exists idx_invites_used_by ON invites(used_by);


-- ===========================
-- upsert
-- ===========================

INSERT INTO users (username, email, password_hash)
VALUES ('john', 'john@example.com', 'hashed_pw')
ON CONFLICT (email)
DO UPDATE
SET username = EXCLUDED.username,
    password_hash = EXCLUDED.password_hash,
    updated_at = CURRENT_TIMESTAMP;

INSERT INTO users (username, email)
VALUES ('john', 'john@example.com')
ON CONFLICT (email)
DO NOTHING;


-- 복합 인덱스 추가로 성능 극대화
CREATE INDEX IF NOT EXISTS idx_posts_user_deleted_id
ON posts(user_id, deleted_at, id DESC)
WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_posts_slug_created
ON posts(slug, created_at DESC, id DESC)
WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_files_post_thumbnail
ON files(post_id, is_thumbnail)
WHERE deleted_at IS NULL AND is_thumbnail = true;

-- ===========================
-- MARKET DASHBOARD TABLES
-- Backs the financial dashboard endpoints (/v1/api/dashboard/*).
-- Contract: dashboard_client_web/types/dashboard.ts + types/history.ts
-- ===========================

-- market_snapshots: one row per dashboard item; covers IDashboardItem /
-- IStockItem (value + change) + ICategoryMeta (as_of, revalidate_seconds) +
-- snapshot fetched_at.
CREATE TABLE if not exists market_snapshots (
    seq int8 GENERATED ALWAYS AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    category            TEXT NOT NULL,
    label               TEXT NOT NULL,
    ticker              TEXT NULL,
    exchange            TEXT NULL,
    value               NUMERIC NOT NULL,
    change_absolute     NUMERIC NOT NULL,
    change_percent      NUMERIC NOT NULL,
    as_of               TIMESTAMPTZ NOT NULL,
    revalidate_seconds  INT NOT NULL,
    fetched_at          TIMESTAMPTZ NOT NULL,
    created_at          TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT market_snapshots_category_check CHECK (category IN ('fx', 'crypto', 'indices', 'rates', 'stocks')),
    CONSTRAINT market_snapshots_pkey PRIMARY KEY (category, label)
);

CREATE INDEX IF NOT EXISTS idx_market_snapshots_category ON market_snapshots(category);

-- market_history: one OHLC candle per item per interval; covers IOHLCPoint
-- grouped by label -> IItemOHLCHistory.
CREATE TABLE if not exists market_history (
    seq int8 GENERATED ALWAYS AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    label       TEXT NOT NULL,
    interval    TEXT NOT NULL,
    bar_time    TIMESTAMPTZ NOT NULL,
    open        NUMERIC NOT NULL,
    high        NUMERIC NOT NULL,
    low         NUMERIC NOT NULL,
    close       NUMERIC NOT NULL,
    volume      BIGINT NOT NULL,
    created_at  TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT market_history_pkey PRIMARY KEY (label, interval, bar_time)
);

CREATE INDEX IF NOT EXISTS idx_market_history_label_interval ON market_history(label, interval, bar_time);


-- ===========================
-- POST_FAVORITES TABLE
-- Per-user blog post favorites (Phase 2 — post-card Save persistence).
-- Composite PK (user_id, post_id) dedupes; insert uses ON CONFLICT DO NOTHING.
-- post_id is a Snowflake BIGINT — read as a STRING end-to-end.
-- ===========================
CREATE TABLE IF NOT EXISTS post_favorites (
    user_id     BIGINT NOT NULL REFERENCES users(id),
    post_id     BIGINT NOT NULL REFERENCES posts(id),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id, post_id)
);

CREATE INDEX IF NOT EXISTS idx_post_favorites_user ON post_favorites(user_id);

-- 0007: index the saved-posts list order (user_id + created_at DESC).
-- Additive; the existing idx_post_favorites_user (user_id) is KEPT.
CREATE INDEX IF NOT EXISTS idx_post_favorites_user_created
    ON post_favorites (user_id, created_at DESC);


-- ===========================
-- POST_LIKES TABLE
-- Per-user blog post LIKES (Phase E — public like count). A like is a PUBLIC
-- approval signal: aggregate COUNT(*) visible to everyone + a per-viewer
-- "did I like this" boolean. Distinct from post_favorites (private bookmark).
-- Composite PK (user_id, post_id) dedupes; insert uses ON CONFLICT DO NOTHING.
-- post_id is a Snowflake BIGINT — read as a STRING end-to-end.
-- Like count is a LIVE COUNT(*) (no denormalized counter), served by
-- idx_post_likes_post. FK ON DELETE: NO ACTION, matching post_favorites for
-- cross-table consistency (db-structure-audit Issue #3).
-- ===========================
CREATE TABLE IF NOT EXISTS post_likes (
    user_id     BIGINT NOT NULL REFERENCES users(id),
    post_id     BIGINT NOT NULL REFERENCES posts(id),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id, post_id)
);

CREATE INDEX IF NOT EXISTS idx_post_likes_post ON post_likes(post_id);


-- ===========================
-- COMMENTS TABLE
-- Threaded reader comments on blog posts (Phase E — Option C). Adjacency-list
-- (parent_id, immutable) PLUS a stored self-inclusive BIGINT[] materialized
-- `path` (path = parent.path || id). The path is the single WRITE-ONCE sort
-- key: WHERE post_id=$1 ORDER BY path yields the whole thread in pre-order DFS
-- with NO WITH RECURSIVE, no zero-padding, no extension. Depth is UNLIMITED
-- (derived cardinality(path)-1, never enforced; client render-collapses).
-- PARALLEL to apps/blog_agent's posts-based tree — does NOT touch
-- posts.parent_id/group_id/level. comments.parent_id self-refs comments(id),
-- NEVER posts. ids are Snowflake BIGINT IDENTITY, read as STRINGS end-to-end.
-- Soft-delete via deleted_at (tombstone, masked at READ — original retained).
-- FK ON DELETE: NO ACTION, matching post_favorites / post_likes for cross-table
-- consistency (db-structure-audit Issue #3).
-- ===========================
CREATE TABLE IF NOT EXISTS comments (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id     BIGINT NOT NULL REFERENCES posts(id),
    user_id     BIGINT NOT NULL REFERENCES users(id),
    parent_id   BIGINT NULL     REFERENCES comments(id),
    path        BIGINT[] NOT NULL,
    body        TEXT NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at  TIMESTAMPTZ NULL
);

CREATE INDEX IF NOT EXISTS idx_comments_post_path ON comments(post_id, path);
CREATE INDEX IF NOT EXISTS idx_comments_parent ON comments(parent_id);

-- =============================================================================
-- Phase I (Phase 2): sticky universe + weekly market-cap ranking series.
-- Mirrors migrations 0011_tracked_symbols.sql + 0012_market_rankings.sql.
-- =============================================================================

-- tracked_symbols: STICKY universe — once ranked, collected forever. Soft-delete
-- (deleted_at) only, manual admin only; weekly re-rank revives via ON CONFLICT.
-- label is UNIQUE (protects the global market_history label namespace).
CREATE TABLE IF NOT EXISTS tracked_symbols (
    symbol          TEXT NOT NULL,
    category        TEXT NOT NULL,
    label           TEXT NOT NULL,
    sector          TEXT NULL,
    source          TEXT NOT NULL DEFAULT 'yahoo',
    exchange        TEXT NULL,
    first_ranked_at TIMESTAMPTZ NULL,
    last_ranked_at  TIMESTAMPTZ NULL,
    created_at      TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    deleted_at      TIMESTAMPTZ NULL,
    CONSTRAINT tracked_symbols_pkey PRIMARY KEY (symbol),
    CONSTRAINT tracked_symbols_label_key UNIQUE (label),
    CONSTRAINT tracked_symbols_category_check CHECK (category IN ('fx', 'crypto', 'indices', 'rates', 'stocks'))
);
CREATE INDEX IF NOT EXISTS idx_tracked_symbols_category ON tracked_symbols(category) WHERE deleted_at IS NULL;

-- market_rankings: append-only weekly time series; ALL tracked symbols per week.
-- scope = 'global' (top-20) or 'sector' (top-10). Idempotent per (as_of,symbol,scope).
CREATE TABLE IF NOT EXISTS market_rankings (
    as_of       DATE NOT NULL,
    symbol      TEXT NOT NULL,
    scope       TEXT NOT NULL,
    sector      TEXT NULL,
    rank        INT NOT NULL,
    market_cap  NUMERIC NULL,
    created_at  TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT market_rankings_pkey PRIMARY KEY (as_of, symbol, scope),
    CONSTRAINT market_rankings_scope_check CHECK (scope IN ('global', 'sector'))
);
CREATE INDEX IF NOT EXISTS idx_market_rankings_asof_scope ON market_rankings(as_of, scope, rank);
CREATE INDEX IF NOT EXISTS idx_market_rankings_scope_asof ON market_rankings (scope, sector, as_of DESC, symbol, rank);
-- =============================================================================
-- Phase I (I2.8): per-symbol fundamentals cache (shares + sector).
-- Mirrors migration 0013_symbol_fundamentals.sql.
-- =============================================================================

-- symbol_fundamentals: caches shares_outstanding (monthly fast_info refresh) and
-- sector (quarterly .info refresh) so the weekly rank derives market_cap =
-- shares x local close WITHOUT a per-symbol .info call. market_cap is NOT stored
-- (derived fresh each week from market_history). Soft-delete (deleted_at) only.
CREATE TABLE IF NOT EXISTS symbol_fundamentals (
    symbol              TEXT NOT NULL,
    shares_outstanding  NUMERIC NULL,
    sector              TEXT NULL,
    shares_refreshed_at TIMESTAMPTZ NULL,
    sector_refreshed_at TIMESTAMPTZ NULL,
    source              TEXT NOT NULL DEFAULT 'yahoo',
    created_at          TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    deleted_at          TIMESTAMPTZ NULL,
    CONSTRAINT symbol_fundamentals_pkey PRIMARY KEY (symbol)
);

-- =============================================================================
-- 0018: add company display name to the fundamentals cache.
-- Mirrors migration 0018_symbol_fundamentals_long_name.sql.
-- =============================================================================
ALTER TABLE symbol_fundamentals
    ADD COLUMN IF NOT EXISTS long_name TEXT NULL;

-- =============================================================================
-- Phase J (SEC 13F): filing-level metadata + per-position rows.
-- Mirrors migration 0017_sec_holdings.sql.
-- Soft-delete on both tables; amendments insert a new accession and the
-- collector soft-deletes the prior same-period filing.
-- =============================================================================

-- One row per (cik, accession) — filing-level metadata.
CREATE TABLE IF NOT EXISTS sec_filings (
    cik               TEXT NOT NULL,                 -- zero-padded 10-char, source-native
    accession         TEXT NOT NULL,                 -- e.g. 0001067983-25-000123
    period_of_report  DATE NOT NULL,                 -- reportDate (quarter-end) = as_of
    form_type         TEXT NOT NULL,                 -- '13F-HR' | '13F-HR/A'
    filer             TEXT NULL,
    filing_date       DATE NULL,
    value_units       TEXT NOT NULL DEFAULT 'usd',   -- 'usd' | 'usd_thousands'
    source            TEXT NOT NULL DEFAULT 'sec13f',
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at        TIMESTAMPTZ NULL,
    CONSTRAINT sec_filings_pkey PRIMARY KEY (cik, accession)
);

CREATE INDEX IF NOT EXISTS idx_sec_filings_cik_period
    ON sec_filings(cik, period_of_report DESC) WHERE deleted_at IS NULL;

-- One row per (cik, accession, cusip, put_call, prn_type). put_call + prn_type
-- are NON-NULL sentinels ('') because Postgres treats NULL as distinct in a
-- unique key, which would silently break the ON CONFLICT upsert.
CREATE TABLE IF NOT EXISTS sec_holdings (
    cik              TEXT NOT NULL,
    accession        TEXT NOT NULL,
    period_of_report DATE NOT NULL,                  -- denormalized for fast as-of reads
    cusip            TEXT NOT NULL,
    name_of_issuer   TEXT NOT NULL,
    title_of_class   TEXT NULL,
    ticker           TEXT NULL,                       -- reserved; CUSIP->ticker via security_map
    shares           BIGINT NULL,                     -- sshPrnamt when type=SH
    prn_type         TEXT NOT NULL DEFAULT '',        -- 'SH' | 'PRN'
    value_usd        BIGINT NOT NULL,                 -- normalized whole USD
    put_call         TEXT NOT NULL DEFAULT '',        -- '' | 'PUT' | 'CALL'
    discretion       TEXT NULL,
    source           TEXT NOT NULL DEFAULT 'sec13f',
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at       TIMESTAMPTZ NULL,
    CONSTRAINT sec_holdings_pkey PRIMARY KEY (cik, accession, cusip, put_call, prn_type)
);

CREATE INDEX IF NOT EXISTS idx_sec_holdings_cik_period
    ON sec_holdings(cik, period_of_report DESC) WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_sec_holdings_cusip
    ON sec_holdings(cusip) WHERE deleted_at IS NULL;

-- =============================================================================
-- Phase P (STEP 0-b): CUSIP -> ticker -> sector join key.
-- Mirrors migration 0019_security_map.sql (table + v_sec_holdings_enriched view).
-- =============================================================================
CREATE TABLE IF NOT EXISTS security_map (
    cusip           TEXT NOT NULL,
    ticker          TEXT NULL,
    name            TEXT NULL,
    sector          TEXT NULL,
    source          TEXT NOT NULL DEFAULT 'openfigi',
    confidence      TEXT NOT NULL DEFAULT 'exact',
    resolved_at     TIMESTAMPTZ NULL,
    attempt_count   INT NOT NULL DEFAULT 0,
    last_attempt_at TIMESTAMPTZ NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at      TIMESTAMPTZ NULL,
    CONSTRAINT security_map_pkey PRIMARY KEY (cusip)
);

CREATE INDEX IF NOT EXISTS idx_security_map_ticker
    ON security_map(ticker) WHERE deleted_at IS NULL AND ticker IS NOT NULL;

-- Enriched read surface: 13F holdings + resolved ticker + sector. sector prefers
-- live symbol_fundamentals, falls back to the mapping-time cached sector.
-- Rows whose CUSIP is unresolved surface mapped_ticker = NULL (naturally excluded
-- from signal math, which requires a ticker).
CREATE OR REPLACE VIEW v_sec_holdings_enriched AS
SELECT h.*,
       m.ticker                      AS mapped_ticker,
       COALESCE(f.sector, m.sector)  AS sector,
       m.confidence                  AS map_confidence
FROM sec_holdings h
LEFT JOIN security_map m
       ON m.cusip = h.cusip AND m.deleted_at IS NULL
LEFT JOIN symbol_fundamentals f
       ON f.symbol = m.ticker AND f.deleted_at IS NULL
WHERE h.deleted_at IS NULL;

-- =============================================================================
-- Phase P (STEP 1): 13F signal analytics. fund_registry classifies filers as
-- active stock-pickers vs passive index funds (consensus uses active only).
-- Mirrors migration 0020_sec_analytics.sql (table + seed + views).
-- =============================================================================
CREATE TABLE IF NOT EXISTS fund_registry (
    cik               TEXT NOT NULL,
    label             TEXT NOT NULL,
    is_active_manager BOOLEAN NOT NULL DEFAULT FALSE,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at        TIMESTAMPTZ NULL,
    CONSTRAINT fund_registry_pkey PRIMARY KEY (cik)
);

INSERT INTO fund_registry (cik, label, is_active_manager) VALUES
    ('0001067983', 'Berkshire Hathaway',       TRUE),
    ('0001350694', 'Bridgewater Associates',   TRUE),
    ('0001037389', 'Renaissance Technologies', TRUE),
    ('0002012383', 'BlackRock',                FALSE),
    ('0000102909', 'Vanguard Group',           FALSE),
    ('0000093751', 'State Street',             FALSE)
ON CONFLICT (cik) DO NOTHING;

-- Base: one row per (cik, period, cusip), summed across accessions, with the
-- fund's in-quarter portfolio weight.
CREATE OR REPLACE VIEW v_sec_positions AS
WITH pos AS (
    SELECT cik, period_of_report, cusip,
           MAX(name_of_issuer) AS name_of_issuer,
           SUM(shares)         AS shares,
           SUM(value_usd)      AS value_usd
    FROM sec_holdings
    WHERE deleted_at IS NULL AND put_call = '' AND prn_type <> 'PRN'
    GROUP BY cik, period_of_report, cusip
)
SELECT p.*,
       ROUND(p.value_usd * 100.0 / NULLIF(
           SUM(p.value_usd) OVER (PARTITION BY cik, period_of_report), 0), 4
       ) AS weight_pct
FROM pos p;

-- Each fund's adjacent filed-quarter ladder (prev_period = the quarter actually
-- filed before this one, NOT calendar-minus-one).
CREATE OR REPLACE VIEW v_sec_fund_periods AS
SELECT cik, period_of_report,
       LAG(period_of_report) OVER (PARTITION BY cik ORDER BY period_of_report) AS prev_period
FROM (
    SELECT DISTINCT cik, period_of_report
    FROM sec_filings WHERE deleted_at IS NULL
) fp;

-- Δ for currently-held positions vs the fund's prior filed quarter.
CREATE OR REPLACE VIEW v_sec_position_delta AS
SELECT cur.cik, cur.period_of_report, cur.cusip, cur.name_of_issuer,
       cur.shares, cur.value_usd, cur.weight_pct,
       fp.prev_period,
       cur.shares     - prev.shares      AS delta_shares,
       cur.weight_pct - prev.weight_pct  AS delta_weight_pct,
       (fp.prev_period IS NOT NULL AND prev.cusip IS NULL) AS is_new,
       (fp.prev_period IS NULL)                            AS is_first_period
FROM v_sec_positions cur
JOIN v_sec_fund_periods fp
  ON fp.cik = cur.cik AND fp.period_of_report = cur.period_of_report
LEFT JOIN v_sec_positions prev
  ON prev.cik = cur.cik AND prev.period_of_report = fp.prev_period
 AND prev.cusip = cur.cusip;

-- EXITs: held in the prior filed quarter, absent now (attributed to this period).
CREATE OR REPLACE VIEW v_sec_exits AS
SELECT fp.cik, fp.period_of_report, prev.cusip, prev.name_of_issuer,
       prev.shares AS prev_shares, prev.weight_pct AS prev_weight_pct
FROM v_sec_fund_periods fp
JOIN v_sec_positions prev
  ON prev.cik = fp.cik AND prev.period_of_report = fp.prev_period
LEFT JOIN v_sec_positions cur
  ON cur.cik = fp.cik AND cur.period_of_report = fp.period_of_report
 AND cur.cusip = prev.cusip
WHERE cur.cusip IS NULL;

-- Cross-fund consensus per (period, cusip): active vs total holder counts.
CREATE OR REPLACE VIEW v_sec_consensus AS
SELECT p.period_of_report, p.cusip,
       MAX(p.name_of_issuer)                                AS name_of_issuer,
       COUNT(*) FILTER (WHERE r.is_active_manager)          AS holder_count_active,
       COUNT(*)                                             AS holder_count_total,
       SUM(p.value_usd) FILTER (WHERE r.is_active_manager)  AS active_value_usd,
       ARRAY_AGG(p.cik ORDER BY p.value_usd DESC)           AS holder_ciks
FROM v_sec_positions p
JOIN fund_registry r ON r.cik = p.cik AND r.deleted_at IS NULL
GROUP BY p.period_of_report, p.cusip;

-- =============================================================================
-- Phase U: 13F options exposure — the complement of v_sec_positions.
-- Mirrors migration 0027_sec_derivatives_exposure.sql.
-- v_sec_positions keeps put_call = '' (long stock); this view keeps
-- put_call IN ('PUT','CALL'), the option legs it discards. One row per
-- (cik, period, cusip) with call vs put notional/shares. Quarterly, coarse
-- derivatives sentiment (NOT gamma/GEX — that is Phase V).
-- =============================================================================
CREATE OR REPLACE VIEW v_sec_derivatives_exposure AS
SELECT cik, period_of_report, cusip,
       MAX(name_of_issuer)                             AS name_of_issuer,
       SUM(value_usd) FILTER (WHERE put_call = 'CALL') AS call_value_usd,
       SUM(value_usd) FILTER (WHERE put_call = 'PUT')  AS put_value_usd,
       SUM(shares)    FILTER (WHERE put_call = 'CALL') AS call_shares,
       SUM(shares)    FILTER (WHERE put_call = 'PUT')  AS put_shares,
       SUM(value_usd)                                  AS derivatives_value_usd
FROM sec_holdings
WHERE deleted_at IS NULL AND put_call IN ('PUT', 'CALL')
GROUP BY cik, period_of_report, cusip;

-- =============================================================================
-- Phase Q: US congressional + executive STOCK Act disclosures.
-- Mirrors migration 0022_politician_trades.sql (tables + indexes + views).
-- Views (v_politician_trades_enriched / v_politician_activity) depend on
-- security_map + symbol_fundamentals, both present in this SSOT.
-- =============================================================================

-- politician_registry: one row per unique filer (member of congress or
-- executive branch official). filer_id is the kadoa filer slug (PK).
CREATE TABLE IF NOT EXISTS politician_registry (
    filer_id        TEXT NOT NULL,
    filer_name      TEXT NOT NULL,
    party           TEXT NULL,                           -- 'D'|'R'|'I'
    chamber         TEXT NULL,                           -- 'house'|'senate'
    branch          TEXT NULL,                           -- 'congress'|'executive'
    state           TEXT NULL,
    office          TEXT NULL,
    agency          TEXT NULL,
    bioguide_id     TEXT NULL,                           -- reserved: congress-legislators enrichment
    source          TEXT NOT NULL DEFAULT 'kadoa',
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at      TIMESTAMPTZ NULL,
    CONSTRAINT politician_registry_pkey PRIMARY KEY (filer_id)
);

-- politician_trades: one row per disclosed transaction event (NOT holdings
-- snapshot). external_id = kadoa id; globally unique → the dedup/upsert key.
CREATE TABLE IF NOT EXISTS politician_trades (
    external_id          TEXT NOT NULL,
    filer_id             TEXT NOT NULL,
    disclosure_date      DATE NOT NULL,
    transaction_date     DATE NULL,
    transaction_type     TEXT NOT NULL,                  -- normalized 'buy'|'sell'|'exchange'
    transaction_type_raw TEXT NULL,
    filer_owner          TEXT NULL,                      -- normalized 'self'|'spouse'|'dependent'|'joint'
    owner_raw            TEXT NULL,
    asset_type           TEXT NOT NULL DEFAULT 'other',  -- 'equity'|'bond'|'option'|'other'
    asset_type_raw       TEXT NULL,
    ticker               TEXT NULL,
    asset_name           TEXT NULL,
    value_min            BIGINT NULL,
    value_max            BIGINT NULL,
    value_estimate       BIGINT NULL,
    value_label          TEXT NULL,
    doc_url              TEXT NULL,
    source_id            TEXT NULL,                      -- 'house_clerk'|'senate_efd'|'oge'
    filing_type          TEXT NULL,                      -- 'PTR'|'278-T'
    days_to_file         INT NULL,
    is_late              BOOLEAN NULL,
    source               TEXT NOT NULL DEFAULT 'kadoa',
    created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at           TIMESTAMPTZ NULL,
    CONSTRAINT politician_trades_pkey PRIMARY KEY (external_id),
    CONSTRAINT politician_trades_filer_fk
        FOREIGN KEY (filer_id) REFERENCES politician_registry(filer_id)
);

CREATE INDEX IF NOT EXISTS idx_politician_trades_ticker_disc
    ON politician_trades(ticker, disclosure_date DESC)
    WHERE deleted_at IS NULL AND ticker IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_politician_trades_disc
    ON politician_trades(disclosure_date DESC)
    WHERE deleted_at IS NULL;

CREATE OR REPLACE VIEW v_politician_trades_enriched AS
SELECT pt.*,
       r.filer_name,
       r.party,
       r.chamber,
       r.branch,
       sm.sector                        AS map_sector,
       COALESCE(f.sector, sm.sector)    AS sector
FROM politician_trades pt
LEFT JOIN politician_registry r
       ON r.filer_id = pt.filer_id AND r.deleted_at IS NULL
LEFT JOIN security_map sm
       ON sm.ticker = pt.ticker AND sm.deleted_at IS NULL
LEFT JOIN symbol_fundamentals f
       ON f.symbol = pt.ticker AND f.deleted_at IS NULL
WHERE pt.deleted_at IS NULL;

-- Aggregate activity per ticker over a rolling 90-day disclosure window.
-- Re-keyed on person identity (COALESCE(bioguide_id, filer_id)) per 0024 so
-- that House→Senate career moves and name-spelling variants count as one member.
-- v_politician_ticker_holders / v_politician_filer_timeline remain filer_id-keyed
-- (per-filer profile pages — out of scope here).
CREATE OR REPLACE VIEW v_politician_activity AS
WITH trades AS (
    SELECT
        pt.ticker,
        pt.transaction_type,
        pt.disclosure_date,
        COALESCE(r.bioguide_id, pt.filer_id) AS person_key
    FROM politician_trades pt
    LEFT JOIN politician_registry r
           ON r.filer_id = pt.filer_id AND r.deleted_at IS NULL
    WHERE pt.ticker IS NOT NULL
      AND pt.deleted_at IS NULL
      AND pt.disclosure_date >= CURRENT_DATE - INTERVAL '90 days'
)
SELECT
    ticker,
    COUNT(DISTINCT person_key)                                                    AS traded_by_count,
    COUNT(DISTINCT person_key) FILTER (WHERE transaction_type = 'buy')            AS buy_member_count,
    COUNT(DISTINCT person_key) FILTER (WHERE transaction_type = 'sell')           AS sell_member_count,
    CASE
        WHEN COUNT(DISTINCT person_key) FILTER (WHERE transaction_type = 'buy')
           > COUNT(DISTINCT person_key) FILTER (WHERE transaction_type = 'sell')
            THEN 'buy_skew'
        WHEN COUNT(DISTINCT person_key) FILTER (WHERE transaction_type = 'sell')
           > COUNT(DISTINCT person_key) FILTER (WHERE transaction_type = 'buy')
            THEN 'sell_skew'
        ELSE 'mixed'
    END                                                                           AS net_direction,
    MAX(disclosure_date)                                                          AS latest_disclosure_date,
    (
        COUNT(DISTINCT person_key) FILTER (WHERE transaction_type = 'buy')  >= 3
        OR
        COUNT(DISTINCT person_key) FILTER (WHERE transaction_type = 'sell') >= 3
    )                                                                             AS cluster_flag
FROM trades
GROUP BY ticker;

ALTER TABLE politician_registry
    ADD COLUMN IF NOT EXISTS photo_url    TEXT   NULL,
    ADD COLUMN IF NOT EXISTS trade_count  INT    NULL,
    ADD COLUMN IF NOT EXISTS purchases    INT    NULL,
    ADD COLUMN IF NOT EXISTS sales        INT    NULL,
    ADD COLUMN IF NOT EXISTS late_filings INT    NULL,
    ADD COLUMN IF NOT EXISTS est_volume   BIGINT NULL;

CREATE OR REPLACE VIEW v_politician_ticker_holders AS
SELECT
    ticker,
    filer_id,
    SUM(value_estimate)                                                  AS disclosed_value_usd,
    COUNT(*)                                                             AS trade_count,
    COUNT(*) FILTER (WHERE transaction_type = 'buy')                     AS buy_count,
    COUNT(*) FILTER (WHERE transaction_type = 'sell')                    AS sell_count,
    CASE
        WHEN COUNT(*) FILTER (WHERE transaction_type = 'buy')
           > COUNT(*) FILTER (WHERE transaction_type = 'sell')
            THEN 'buy_skew'
        WHEN COUNT(*) FILTER (WHERE transaction_type = 'sell')
           > COUNT(*) FILTER (WHERE transaction_type = 'buy')
            THEN 'sell_skew'
        ELSE 'mixed'
    END                                                                  AS net_direction,
    MAX(disclosure_date)                                                 AS latest_disclosure,
    MIN(disclosure_date)                                                 AS first_disclosure
FROM politician_trades
WHERE ticker IS NOT NULL
  AND deleted_at IS NULL
GROUP BY ticker, filer_id;

CREATE OR REPLACE VIEW v_politician_filer_timeline AS
SELECT
    filer_id,
    ticker,
    date_trunc('quarter', transaction_date)::date                                                AS quarter,
    COALESCE(SUM(value_estimate) FILTER (WHERE transaction_type = 'buy'), 0)
        - COALESCE(SUM(value_estimate) FILTER (WHERE transaction_type = 'sell'), 0)             AS net_value_usd,
    COUNT(*) FILTER (WHERE transaction_type = 'buy')                                             AS buy_count,
    COUNT(*) FILTER (WHERE transaction_type = 'sell')                                            AS sell_count,
    CASE
        WHEN COUNT(*) FILTER (WHERE transaction_type = 'buy')
           > COUNT(*) FILTER (WHERE transaction_type = 'sell')
            THEN 'buy'
        WHEN COUNT(*) FILTER (WHERE transaction_type = 'sell')
           > COUNT(*) FILTER (WHERE transaction_type = 'buy')
            THEN 'sell'
        ELSE 'mixed'
    END                                                                                          AS direction
FROM politician_trades
WHERE ticker IS NOT NULL
  AND transaction_date IS NOT NULL
  AND deleted_at IS NULL
GROUP BY filer_id, ticker, date_trunc('quarter', transaction_date);

-- Mirrors migration 0025_politician_committees.sql (committee membership + sector map).

CREATE TABLE IF NOT EXISTS politician_committees (
    bioguide_id          TEXT        NOT NULL,
    committee_thomas_id  TEXT        NOT NULL,
    committee_name       TEXT        NOT NULL,
    committee_type       TEXT        NOT NULL,
    title                TEXT            NULL,
    source               TEXT        NOT NULL DEFAULT 'congress-legislators',
    created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at           TIMESTAMPTZ         NULL,
    PRIMARY KEY (bioguide_id, committee_thomas_id)
);

CREATE TABLE IF NOT EXISTS committee_sector_map (
    committee_thomas_id  TEXT  NOT NULL,
    sector               TEXT  NOT NULL,
    PRIMARY KEY (committee_thomas_id, sector)
);

CREATE OR REPLACE VIEW v_politician_sector_oversight AS
SELECT DISTINCT
    pc.bioguide_id,
    csm.sector
FROM politician_committees pc
JOIN committee_sector_map csm
    ON csm.committee_thomas_id = pc.committee_thomas_id
WHERE pc.deleted_at IS NULL;

-- Mirrors migration 0028_signal_backtest.sql (Phase R event-study / forward-return harness).

CREATE TABLE IF NOT EXISTS signal_backtest (
    signal_type  TEXT        NOT NULL,
    ticker       TEXT        NOT NULL,
    as_of        DATE        NOT NULL,
    horizon_days INT         NOT NULL,
    car          NUMERIC         NULL,
    is_hit       BOOLEAN         NULL,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at   TIMESTAMPTZ         NULL,
    CONSTRAINT signal_backtest_pkey PRIMARY KEY (signal_type, ticker, as_of, horizon_days)
);

CREATE OR REPLACE VIEW v_signal_backtest_summary AS
SELECT
    signal_type,
    horizon_days,
    AVG(car)                                                               AS mean_car,
    AVG(is_hit::int)                                                       AS hit_rate,
    COUNT(*)                                                               AS n,
    AVG(car) / NULLIF(STDDEV_SAMP(car) / SQRT(COUNT(*)), 0)               AS t_stat
FROM signal_backtest
WHERE deleted_at IS NULL
  AND car IS NOT NULL
GROUP BY signal_type, horizon_days
ORDER BY signal_type, horizon_days;

-- Mirrors migration 0031_sec_new_positions_mapped.sql (Phase R.6 — fast 13F source).
-- Supersedes 0029: pushes the security_map (mapped-CUSIP) filter DOWN into the
-- position CTE so the new-position self-join runs on ~250 mapped CUSIPs, not all
-- of sec_holdings. REFRESH went from >600s to ~5s. Populated WITH DATA.
CREATE MATERIALIZED VIEW IF NOT EXISTS mv_sec_new_positions AS
WITH mapped AS (
    SELECT DISTINCT cusip, ticker FROM security_map
    WHERE deleted_at IS NULL AND ticker IS NOT NULL
),
pos AS (
    SELECT h.cik, h.period_of_report, h.cusip
    FROM sec_holdings h JOIN mapped m ON m.cusip = h.cusip
    WHERE h.deleted_at IS NULL AND h.put_call = '' AND h.prn_type <> 'PRN'
    GROUP BY h.cik, h.period_of_report, h.cusip
),
periods AS (
    SELECT cik, period_of_report,
           LAG(period_of_report) OVER (PARTITION BY cik ORDER BY period_of_report) AS prev_period
    FROM (SELECT DISTINCT cik, period_of_report FROM sec_filings WHERE deleted_at IS NULL) fp
),
newpos AS (
    SELECT cur.cik, cur.period_of_report, cur.cusip
    FROM pos cur
    JOIN periods p ON p.cik = cur.cik AND p.period_of_report = cur.period_of_report
    LEFT JOIN pos prev ON prev.cik = cur.cik
        AND prev.period_of_report = p.prev_period AND prev.cusip = cur.cusip
    WHERE p.prev_period IS NOT NULL AND prev.cusip IS NULL
)
SELECT n.cik, n.period_of_report, n.cusip, m.ticker, f.filing_date
FROM newpos n
JOIN mapped m ON m.cusip = n.cusip
JOIN (
    SELECT cik, period_of_report, MIN(filing_date) AS filing_date
    FROM sec_filings WHERE filing_date IS NOT NULL AND deleted_at IS NULL
    GROUP BY cik, period_of_report
) f ON f.cik = n.cik AND f.period_of_report = n.period_of_report
WITH DATA;

CREATE UNIQUE INDEX IF NOT EXISTS mv_sec_new_positions_pk
    ON mv_sec_new_positions (cik, cusip, period_of_report);
CREATE INDEX IF NOT EXISTS mv_sec_new_positions_filing_idx
    ON mv_sec_new_positions (filing_date);

-- Mirrors migration 0030_gex_daily.sql (Phase V-collect — gamma exposure daily scalar).
-- Derived daily GEX per underlying (raw option chains never stored). Dealer-centric
-- sign: calls +, puts − ; net_gex = call_gex − put_gex ($ per 1% spot move).
-- call_gex/put_gex stored unsigned (sign is in the column name).
CREATE TABLE IF NOT EXISTS gex_daily (
    as_of       DATE    NOT NULL,
    ticker      TEXT    NOT NULL,
    net_gex     NUMERIC NOT NULL,
    call_gex    NUMERIC NOT NULL,
    put_gex     NUMERIC NOT NULL,
    spot        NUMERIC NOT NULL,
    source      TEXT    NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at  TIMESTAMPTZ,
    PRIMARY KEY (as_of, ticker)
);
CREATE INDEX IF NOT EXISTS idx_gex_daily_active_ticker
    ON gex_daily (ticker, as_of DESC)
    WHERE deleted_at IS NULL;
